`QRDecomposition` Gram-Schmidt algorithm
Pankin610/linalg pull request #15
Opened 2022-05-04 21:50 UTC by FiIipson

Please review the code. I hope that algorithm works (it passed all the tests) however I'd be glad to resolve any issue.

2022-05-04 21:53 UTC, FiIipson commented
At this moment I don't know how to deal with making the class as private as it could be and still test it.

2022-05-07 19:44 UTC, Pankin610 requested changes
It would be nice to have a QrDecomposition interface that would be implemented by this class (With GramScmidt), especially considering that we will make different QR implementations

2022-05-07 19:48 UTC, Pankin610 requested changes

2022-05-07 19:48 UTC, Pankin610 commented on java/src/main/java/linalg/algorithms/QRDecompositionGramSchmidt.java
> +    double ScalarProduct(Vector a, Vector b) {
This is already implemented in VectorUtils, we shouldn't write the same thing twice

2022-05-07 19:48 UTC, Pankin610 commented on java/src/main/java/linalg/algorithms/QRDecompositionGramSchmidt.java
> +    Matrix Transpose(Matrix a) {
As previously discussed we decided to replace this with separate Matrix.Transpose method

2022-05-08 12:08 UTC, Pankin610 commented
Good job, thanks for fixing the issues

2022-05-08 12:09 UTC, Pankin610 approved these changes

2022-05-08 12:10 UTC, merged