Some simple tests for `DenseMatrix` class
Pankin610/linalg pull request #8
Opened 2022-04-30 13:58 UTC by FiIipson

2022-04-30 15:26 UTC, Pankin610 approved these changes
Nice code bro, great test names and code style.

2022-04-30 16:06 UTC, FiIipson commented
> Nice code bro, great test names and code style.

Thanks for the review :muscle:

2022-04-30 16:12 UTC, FiIipson commented
**Please do not merge this branch by the end of day** still updating new stuff.

2022-05-01 13:08 UTC, Pankin610 requested changes

2022-05-01 13:10 UTC, FiIipson commented on java/src/test/java/linalg/matrix/COOMatrixTest.java
> +      Assertions.assertEquals(i, new COOMatrix(new HashMap<>(), i, i + new Random().nextInt(test_size)).Rows());
Indeed, forgot about that rule - usually my IDE does it for me

2022-05-01 13:17 UTC, merged